"""Create subdomain table

Revision ID: 6293759d13ec
Revises: fae1dffbf3da
Create Date: 2024-12-13 03:38:24.312215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6293759d13ec'
down_revision: Union[str, None] = 'fae1dffbf3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('target_domain', sa.String(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subdomains')
    # ### end Alembic commands ###
