"""Add more columns in subdomain table

Revision ID: 71d7ed1b7248
Revises: 6293759d13ec
Create Date: 2024-12-13 23:06:57.216330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d7ed1b7248'
down_revision: Union[str, None] = '6293759d13ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdomains', sa.Column('record_type', sa.String(), nullable=True))
    op.add_column('subdomains', sa.Column('ttl', sa.Integer(), nullable=True))
    op.add_column('subdomains', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subdomains', 'priority')
    op.drop_column('subdomains', 'ttl')
    op.drop_column('subdomains', 'record_type')
    # ### end Alembic commands ###
